//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace transparent.pages.googlemaps {
    
    
    public partial class Demo2 {
        
        /// <summary>
        /// GoogleDemo21 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::transparent.controls.googlemaps.GoogleDemo2 GoogleDemo21;
    }
}
