<%@ Control Language="C#" AutoEventWireup="true" CodeBehind="IntegUserControl.ascx.cs" Inherits="transparent.controls.usercontrols.IntegUserControl" %>
<%@ Register TagName="sourceviewer" TagPrefix="uc2" Src="~/include/ctl/SourceViewer.ascx" %>
<div class="pageSectionDiv">
<span runat="server" id="lOut"  />
<br/>
<span>[This section generated by <strong><asp:Literal runat="server" ID="lClassName" /></strong>]</span>
<br />
<uc2:sourceviewer id="SourceViewer2" runat="server" />
</div>
